
export const SEARCH_REPO = 'SEARCH_REPO';
export const SEARCH_ORG = 'SEARCH_ORG';
export const RESET_SEARCH = 'RESET_SEARCH';
export const SET_LOADING_ORGS = 'SET_LOADING_ORGS';
export const SET_LOADING_REPOS = 'SET_LOADING_REPOS';
export const INCREMENT_REPO_COUNTER = 'INCREMENT_REPO_COUNTER';
export const INCREMENT_ORG_COUNTER = 'INCREMENT_ORG_COUNTER';
export const FULL_SEARCH = 'FULL_SEARCH';
export const LOAD_MORE_REPO = 'LOAD_MORE_REPO';
export const LOAD_MORE_ORG = 'LOAD_MORE_ORG';
export const RESET_COUNTERS = 'RESET_COUNTERS';
export const SET_TEXT = 'SET_TEXT';
export const SET_HOME_TEXT = 'SET_HOME_TEXT';